### ISSUE TITLE
SettingCallback.instance  实例化疑问

### ISSUE THREAD

**Issue by lexigua** [NancoHu/DingtalkCallbackService#1]
public static SettingCallback GetInstance(TransmitData transmitData)
        {
            if (instance == null)
            {
                lock (locker)
                {
                    if (instance == null)
                    {
                        SettingCallback instance = new SettingCallback(transmitData);  
                    }
                }
                return instance;
            }
            instance.access_token = instance.gettoken(transmitData.appKey, transmitData.appSecret);
            return instance;
        }
________________________________________________
您好. 我对以上代码有些疑问
SettingCallback instance = new SettingCallback(transmitData);  
这样的话好像SettingCallback.instance 一直为null ,并没有地方对它实例化

**Comment by chuck9090** [comment]
已修复
